<?xml version="1.0" encoding="utf-8"?><Database Name="oxcoder" Class="ChallengeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CHENRN-PC;Initial Catalog=oxcoder;Integrated Security=True" SettingsObjectName="Model.Properties.Settings" SettingsPropertyName="oxcoderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.challenge" Member="challenge">
    <Type Name="challenge">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="chanllengeLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isPhoto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isPublished" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="question" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="companyEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="publishTime" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
  <Table Name="dbo.challengeRecord" Member="challengeRecord">
    <Type Name="challengeRecord">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="chanllengeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="coderEmail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="result" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="subResult" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="time" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="subTime" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="isInvited" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.coder" Member="coder">
    <Type Name="coder">
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="sex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="performance" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="performanceperccent" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="bindinginfo" Type="System.String" DbType="NVarChar(7) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.enterprise" Member="enterprise">
    <Type Name="enterprise">
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="shortName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="fullName" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="introduction" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="scale" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="website" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="logo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="label" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ischeck" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="restInvite" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="restCreate" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[order]" Member="order">
    <Type Name="order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="company" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="money" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.promoCode" Member="promoCode">
    <Type Name="promoCode">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="value" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="inviteCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.question" Member="question">
    <Type Name="question">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="intro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="knowledge" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="tecnology" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="questionLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="questionContent" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="answer" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="typeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.type" Member="type">
    <Type Name="type">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="content" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="user">
    <Type Name="user">
      <Column Name="email" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>