#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="oxcoder")]
	public partial class ChallengeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertchallenge(challenge instance);
    partial void Updatechallenge(challenge instance);
    partial void Deletechallenge(challenge instance);
    partial void InsertchallengeRecord(challengeRecord instance);
    partial void UpdatechallengeRecord(challengeRecord instance);
    partial void DeletechallengeRecord(challengeRecord instance);
    partial void Insertcoder(coder instance);
    partial void Updatecoder(coder instance);
    partial void Deletecoder(coder instance);
    partial void Insertenterprise(enterprise instance);
    partial void Updateenterprise(enterprise instance);
    partial void Deleteenterprise(enterprise instance);
    partial void InsertpromoCode(promoCode instance);
    partial void UpdatepromoCode(promoCode instance);
    partial void DeletepromoCode(promoCode instance);
    partial void Insertquestion(question instance);
    partial void Updatequestion(question instance);
    partial void Deletequestion(question instance);
    partial void Inserttype(type instance);
    partial void Updatetype(type instance);
    partial void Deletetype(type instance);
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    #endregion
		
		public ChallengeDataContext() : 
				base(global::Model.Properties.Settings.Default.oxcoderConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChallengeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChallengeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChallengeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChallengeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<challenge> challenge
		{
			get
			{
				return this.GetTable<challenge>();
			}
		}
		
		public System.Data.Linq.Table<challengeRecord> challengeRecord
		{
			get
			{
				return this.GetTable<challengeRecord>();
			}
		}
		
		public System.Data.Linq.Table<coder> coder
		{
			get
			{
				return this.GetTable<coder>();
			}
		}
		
		public System.Data.Linq.Table<enterprise> enterprise
		{
			get
			{
				return this.GetTable<enterprise>();
			}
		}
		
		public System.Data.Linq.Table<order> order
		{
			get
			{
				return this.GetTable<order>();
			}
		}
		
		public System.Data.Linq.Table<promoCode> promoCode
		{
			get
			{
				return this.GetTable<promoCode>();
			}
		}
		
		public System.Data.Linq.Table<question> question
		{
			get
			{
				return this.GetTable<question>();
			}
		}
		
		public System.Data.Linq.Table<type> type
		{
			get
			{
				return this.GetTable<type>();
			}
		}
		
		public System.Data.Linq.Table<user> user
		{
			get
			{
				return this.GetTable<user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.challenge")]
	public partial class challenge : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _type;
		
		private int _chanllengeLevel;
		
		private System.Nullable<int> _isPhoto;
		
		private System.Nullable<int> _isPublished;
		
		private string _question;
		
		private string _companyEmail;
		
		private System.Nullable<int> _state;
		
		private System.Data.Linq.Binary _publishTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    partial void OnchanllengeLevelChanging(int value);
    partial void OnchanllengeLevelChanged();
    partial void OnisPhotoChanging(System.Nullable<int> value);
    partial void OnisPhotoChanged();
    partial void OnisPublishedChanging(System.Nullable<int> value);
    partial void OnisPublishedChanged();
    partial void OnquestionChanging(string value);
    partial void OnquestionChanged();
    partial void OncompanyEmailChanging(string value);
    partial void OncompanyEmailChanged();
    partial void OnstateChanging(System.Nullable<int> value);
    partial void OnstateChanged();
    partial void OnpublishTimeChanging(System.Data.Linq.Binary value);
    partial void OnpublishTimeChanged();
    #endregion
		
		public challenge()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chanllengeLevel", DbType="Int NOT NULL", UpdateCheck=UpdateCheck.Never)]
		public int chanllengeLevel
		{
			get
			{
				return this._chanllengeLevel;
			}
			set
			{
				if ((this._chanllengeLevel != value))
				{
					this.OnchanllengeLevelChanging(value);
					this.SendPropertyChanging();
					this._chanllengeLevel = value;
					this.SendPropertyChanged("chanllengeLevel");
					this.OnchanllengeLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isPhoto", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> isPhoto
		{
			get
			{
				return this._isPhoto;
			}
			set
			{
				if ((this._isPhoto != value))
				{
					this.OnisPhotoChanging(value);
					this.SendPropertyChanging();
					this._isPhoto = value;
					this.SendPropertyChanged("isPhoto");
					this.OnisPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isPublished", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> isPublished
		{
			get
			{
				return this._isPublished;
			}
			set
			{
				if ((this._isPublished != value))
				{
					this.OnisPublishedChanging(value);
					this.SendPropertyChanging();
					this._isPublished = value;
					this.SendPropertyChanged("isPublished");
					this.OnisPublishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question", DbType="NVarChar(20) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string question
		{
			get
			{
				return this._question;
			}
			set
			{
				if ((this._question != value))
				{
					this.OnquestionChanging(value);
					this.SendPropertyChanging();
					this._question = value;
					this.SendPropertyChanged("question");
					this.OnquestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string companyEmail
		{
			get
			{
				return this._companyEmail;
			}
			set
			{
				if ((this._companyEmail != value))
				{
					this.OncompanyEmailChanging(value);
					this.SendPropertyChanging();
					this._companyEmail = value;
					this.SendPropertyChanged("companyEmail");
					this.OncompanyEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publishTime", AutoSync=AutoSync.Always, DbType="rowversion", IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary publishTime
		{
			get
			{
				return this._publishTime;
			}
			set
			{
				if ((this._publishTime != value))
				{
					this.OnpublishTimeChanging(value);
					this.SendPropertyChanging();
					this._publishTime = value;
					this.SendPropertyChanged("publishTime");
					this.OnpublishTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.challengeRecord")]
	public partial class challengeRecord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _chanllengeId;
		
		private string _coderEmail;
		
		private string _result;
		
		private string _subResult;
		
		private string _time;
		
		private string _subTime;
		
		private System.Nullable<int> _isInvited;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnchanllengeIdChanging(int value);
    partial void OnchanllengeIdChanged();
    partial void OncoderEmailChanging(string value);
    partial void OncoderEmailChanged();
    partial void OnresultChanging(string value);
    partial void OnresultChanged();
    partial void OnsubResultChanging(string value);
    partial void OnsubResultChanged();
    partial void OntimeChanging(string value);
    partial void OntimeChanged();
    partial void OnsubTimeChanging(string value);
    partial void OnsubTimeChanged();
    partial void OnisInvitedChanging(System.Nullable<int> value);
    partial void OnisInvitedChanged();
    #endregion
		
		public challengeRecord()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chanllengeId", DbType="Int NOT NULL")]
		public int chanllengeId
		{
			get
			{
				return this._chanllengeId;
			}
			set
			{
				if ((this._chanllengeId != value))
				{
					this.OnchanllengeIdChanging(value);
					this.SendPropertyChanging();
					this._chanllengeId = value;
					this.SendPropertyChanged("chanllengeId");
					this.OnchanllengeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coderEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string coderEmail
		{
			get
			{
				return this._coderEmail;
			}
			set
			{
				if ((this._coderEmail != value))
				{
					this.OncoderEmailChanging(value);
					this.SendPropertyChanging();
					this._coderEmail = value;
					this.SendPropertyChanged("coderEmail");
					this.OncoderEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result", DbType="NVarChar(30)")]
		public string result
		{
			get
			{
				return this._result;
			}
			set
			{
				if ((this._result != value))
				{
					this.OnresultChanging(value);
					this.SendPropertyChanging();
					this._result = value;
					this.SendPropertyChanged("result");
					this.OnresultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subResult", DbType="NVarChar(50)")]
		public string subResult
		{
			get
			{
				return this._subResult;
			}
			set
			{
				if ((this._subResult != value))
				{
					this.OnsubResultChanging(value);
					this.SendPropertyChanging();
					this._subResult = value;
					this.SendPropertyChanged("subResult");
					this.OnsubResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="NVarChar(10)")]
		public string time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subTime", DbType="NVarChar(30)")]
		public string subTime
		{
			get
			{
				return this._subTime;
			}
			set
			{
				if ((this._subTime != value))
				{
					this.OnsubTimeChanging(value);
					this.SendPropertyChanging();
					this._subTime = value;
					this.SendPropertyChanged("subTime");
					this.OnsubTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isInvited", DbType="Int")]
		public System.Nullable<int> isInvited
		{
			get
			{
				return this._isInvited;
			}
			set
			{
				if ((this._isInvited != value))
				{
					this.OnisInvitedChanging(value);
					this.SendPropertyChanging();
					this._isInvited = value;
					this.SendPropertyChanged("isInvited");
					this.OnisInvitedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.coder")]
	public partial class coder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _email;
		
		private string _name;
		
		private int _age;
		
		private int _sex;
		
		private string _phone;
		
		private string _performance;
		
		private string _performanceperccent;
		
		private string _bindinginfo;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnageChanging(int value);
    partial void OnageChanged();
    partial void OnsexChanging(int value);
    partial void OnsexChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnperformanceChanging(string value);
    partial void OnperformanceChanged();
    partial void OnperformanceperccentChanging(string value);
    partial void OnperformanceperccentChanged();
    partial void OnbindinginfoChanging(string value);
    partial void OnbindinginfoChanged();
    #endregion
		
		public coder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int NOT NULL")]
		public int age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="Int NOT NULL")]
		public int sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(11)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performance", DbType="VarChar(30)")]
		public string performance
		{
			get
			{
				return this._performance;
			}
			set
			{
				if ((this._performance != value))
				{
					this.OnperformanceChanging(value);
					this.SendPropertyChanging();
					this._performance = value;
					this.SendPropertyChanged("performance");
					this.OnperformanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_performanceperccent", DbType="NVarChar(40)")]
		public string performanceperccent
		{
			get
			{
				return this._performanceperccent;
			}
			set
			{
				if ((this._performanceperccent != value))
				{
					this.OnperformanceperccentChanging(value);
					this.SendPropertyChanging();
					this._performanceperccent = value;
					this.SendPropertyChanged("performanceperccent");
					this.OnperformanceperccentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bindinginfo", DbType="NVarChar(7) NOT NULL", CanBeNull=false)]
		public string bindinginfo
		{
			get
			{
				return this._bindinginfo;
			}
			set
			{
				if ((this._bindinginfo != value))
				{
					this.OnbindinginfoChanging(value);
					this.SendPropertyChanging();
					this._bindinginfo = value;
					this.SendPropertyChanged("bindinginfo");
					this.OnbindinginfoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.enterprise")]
	public partial class enterprise : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _email;
		
		private string _shortName;
		
		private string _fullName;
		
		private string _location;
		
		private string _introduction;
		
		private string _scale;
		
		private string _website;
		
		private string _logo;
		
		private string _label;
		
		private int _ischeck;
		
		private System.Nullable<int> _restInvite;
		
		private System.Nullable<int> _restCreate;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnshortNameChanging(string value);
    partial void OnshortNameChanged();
    partial void OnfullNameChanging(string value);
    partial void OnfullNameChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void OnintroductionChanging(string value);
    partial void OnintroductionChanged();
    partial void OnscaleChanging(string value);
    partial void OnscaleChanged();
    partial void OnwebsiteChanging(string value);
    partial void OnwebsiteChanged();
    partial void OnlogoChanging(string value);
    partial void OnlogoChanged();
    partial void OnlabelChanging(string value);
    partial void OnlabelChanged();
    partial void OnischeckChanging(int value);
    partial void OnischeckChanged();
    partial void OnrestInviteChanging(System.Nullable<int> value);
    partial void OnrestInviteChanged();
    partial void OnrestCreateChanging(System.Nullable<int> value);
    partial void OnrestCreateChanged();
    #endregion
		
		public enterprise()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortName", DbType="NVarChar(20)")]
		public string shortName
		{
			get
			{
				return this._shortName;
			}
			set
			{
				if ((this._shortName != value))
				{
					this.OnshortNameChanging(value);
					this.SendPropertyChanging();
					this._shortName = value;
					this.SendPropertyChanged("shortName");
					this.OnshortNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", DbType="NVarChar(40)")]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this.OnfullNameChanging(value);
					this.SendPropertyChanging();
					this._fullName = value;
					this.SendPropertyChanged("fullName");
					this.OnfullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(80)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_introduction", DbType="NVarChar(200)")]
		public string introduction
		{
			get
			{
				return this._introduction;
			}
			set
			{
				if ((this._introduction != value))
				{
					this.OnintroductionChanging(value);
					this.SendPropertyChanging();
					this._introduction = value;
					this.SendPropertyChanged("introduction");
					this.OnintroductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scale", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string scale
		{
			get
			{
				return this._scale;
			}
			set
			{
				if ((this._scale != value))
				{
					this.OnscaleChanging(value);
					this.SendPropertyChanging();
					this._scale = value;
					this.SendPropertyChanged("scale");
					this.OnscaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="NVarChar(30)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this.OnwebsiteChanging(value);
					this.SendPropertyChanging();
					this._website = value;
					this.SendPropertyChanged("website");
					this.OnwebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="NVarChar(30)")]
		public string logo
		{
			get
			{
				return this._logo;
			}
			set
			{
				if ((this._logo != value))
				{
					this.OnlogoChanging(value);
					this.SendPropertyChanging();
					this._logo = value;
					this.SendPropertyChanged("logo");
					this.OnlogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_label", DbType="NVarChar(30)")]
		public string label
		{
			get
			{
				return this._label;
			}
			set
			{
				if ((this._label != value))
				{
					this.OnlabelChanging(value);
					this.SendPropertyChanging();
					this._label = value;
					this.SendPropertyChanged("label");
					this.OnlabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ischeck", DbType="Int NOT NULL")]
		public int ischeck
		{
			get
			{
				return this._ischeck;
			}
			set
			{
				if ((this._ischeck != value))
				{
					this.OnischeckChanging(value);
					this.SendPropertyChanging();
					this._ischeck = value;
					this.SendPropertyChanged("ischeck");
					this.OnischeckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_restInvite", DbType="Int")]
		public System.Nullable<int> restInvite
		{
			get
			{
				return this._restInvite;
			}
			set
			{
				if ((this._restInvite != value))
				{
					this.OnrestInviteChanging(value);
					this.SendPropertyChanging();
					this._restInvite = value;
					this.SendPropertyChanged("restInvite");
					this.OnrestInviteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_restCreate", DbType="Int")]
		public System.Nullable<int> restCreate
		{
			get
			{
				return this._restCreate;
			}
			set
			{
				if ((this._restCreate != value))
				{
					this.OnrestCreateChanging(value);
					this.SendPropertyChanging();
					this._restCreate = value;
					this.SendPropertyChanged("restCreate");
					this.OnrestCreateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[order]")]
	public partial class order
	{
		
		private int _id;
		
		private string _company;
		
		private System.Nullable<int> _type;
		
		private string _money;
		
		public order()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="NVarChar(50)")]
		public string company
		{
			get
			{
				return this._company;
			}
			set
			{
				if ((this._company != value))
				{
					this._company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int")]
		public System.Nullable<int> type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_money", DbType="NVarChar(30)")]
		public string money
		{
			get
			{
				return this._money;
			}
			set
			{
				if ((this._money != value))
				{
					this._money = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.promoCode")]
	public partial class promoCode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _value;
		
		private System.Nullable<int> _inviteCount;
		
		private System.Nullable<int> _createCount;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void OninviteCountChanging(System.Nullable<int> value);
    partial void OninviteCountChanged();
    partial void OncreateCountChanging(System.Nullable<int> value);
    partial void OncreateCountChanged();
    #endregion
		
		public promoCode()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(10)")]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inviteCount", DbType="Int")]
		public System.Nullable<int> inviteCount
		{
			get
			{
				return this._inviteCount;
			}
			set
			{
				if ((this._inviteCount != value))
				{
					this.OninviteCountChanging(value);
					this.SendPropertyChanging();
					this._inviteCount = value;
					this.SendPropertyChanged("inviteCount");
					this.OninviteCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createCount", DbType="Int")]
		public System.Nullable<int> createCount
		{
			get
			{
				return this._createCount;
			}
			set
			{
				if ((this._createCount != value))
				{
					this.OncreateCountChanging(value);
					this.SendPropertyChanging();
					this._createCount = value;
					this.SendPropertyChanged("createCount");
					this.OncreateCountChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.question")]
	public partial class question : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _intro;
		
		private string _knowledge;
		
		private string _tecnology;
		
		private System.Nullable<int> _questionLevel;
		
		private string _questionContent;
		
		private string _answer;
		
		private System.Nullable<int> _typeId;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnintroChanging(string value);
    partial void OnintroChanged();
    partial void OnknowledgeChanging(string value);
    partial void OnknowledgeChanged();
    partial void OntecnologyChanging(string value);
    partial void OntecnologyChanged();
    partial void OnquestionLevelChanging(System.Nullable<int> value);
    partial void OnquestionLevelChanged();
    partial void OnquestionContentChanging(string value);
    partial void OnquestionContentChanged();
    partial void OnanswerChanging(string value);
    partial void OnanswerChanged();
    partial void OntypeIdChanging(System.Nullable<int> value);
    partial void OntypeIdChanged();
    #endregion
		
		public question()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(20)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_intro", DbType="NVarChar(50)")]
		public string intro
		{
			get
			{
				return this._intro;
			}
			set
			{
				if ((this._intro != value))
				{
					this.OnintroChanging(value);
					this.SendPropertyChanging();
					this._intro = value;
					this.SendPropertyChanged("intro");
					this.OnintroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_knowledge", DbType="NVarChar(30)")]
		public string knowledge
		{
			get
			{
				return this._knowledge;
			}
			set
			{
				if ((this._knowledge != value))
				{
					this.OnknowledgeChanging(value);
					this.SendPropertyChanging();
					this._knowledge = value;
					this.SendPropertyChanged("knowledge");
					this.OnknowledgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tecnology", DbType="NVarChar(20)")]
		public string tecnology
		{
			get
			{
				return this._tecnology;
			}
			set
			{
				if ((this._tecnology != value))
				{
					this.OntecnologyChanging(value);
					this.SendPropertyChanging();
					this._tecnology = value;
					this.SendPropertyChanged("tecnology");
					this.OntecnologyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionLevel", DbType="Int")]
		public System.Nullable<int> questionLevel
		{
			get
			{
				return this._questionLevel;
			}
			set
			{
				if ((this._questionLevel != value))
				{
					this.OnquestionLevelChanging(value);
					this.SendPropertyChanging();
					this._questionLevel = value;
					this.SendPropertyChanged("questionLevel");
					this.OnquestionLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_questionContent", DbType="NVarChar(30)")]
		public string questionContent
		{
			get
			{
				return this._questionContent;
			}
			set
			{
				if ((this._questionContent != value))
				{
					this.OnquestionContentChanging(value);
					this.SendPropertyChanging();
					this._questionContent = value;
					this.SendPropertyChanged("questionContent");
					this.OnquestionContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer", DbType="NVarChar(30)")]
		public string answer
		{
			get
			{
				return this._answer;
			}
			set
			{
				if ((this._answer != value))
				{
					this.OnanswerChanging(value);
					this.SendPropertyChanging();
					this._answer = value;
					this.SendPropertyChanged("answer");
					this.OnanswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typeId", DbType="Int")]
		public System.Nullable<int> typeId
		{
			get
			{
				return this._typeId;
			}
			set
			{
				if ((this._typeId != value))
				{
					this.OntypeIdChanging(value);
					this.SendPropertyChanging();
					this._typeId = value;
					this.SendPropertyChanged("typeId");
					this.OntypeIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.type")]
	public partial class type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _content;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OncontentChanging(string value);
    partial void OncontentChanged();
    #endregion
		
		public type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(30)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_content", DbType="NVarChar(200)")]
		public string content
		{
			get
			{
				return this._content;
			}
			set
			{
				if ((this._content != value))
				{
					this.OncontentChanging(value);
					this.SendPropertyChanging();
					this._content = value;
					this.SendPropertyChanged("content");
					this.OncontentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _email;
		
		private string _password;
		
		private int _type;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL")]
		public int type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
